// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCABkVDpSQJar5BjzijH2Re1d6sNuUY6pM',
    appId: '1:17377405565:web:1e68f6d8e83e54fead5f14',
    messagingSenderId: '17377405565',
    projectId: 'thexeason-cd2ab',
    authDomain: 'thexeason-cd2ab.firebaseapp.com',
    storageBucket: 'thexeason-cd2ab.firebasestorage.app',
    measurementId: 'G-8JKJFPJZC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzft_EL13OT0ybaFRjXlvEy9DCEBXcQrU',
    appId: '1:17377405565:android:2767517162bf64baad5f14',
    messagingSenderId: '17377405565',
    projectId: 'thexeason-cd2ab',
    storageBucket: 'thexeason-cd2ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzQUeeExHC-wEGTD6jH6GbhM8Y1s_Dnyo',
    appId: '1:17377405565:ios:2395ccadefafecc9ad5f14',
    messagingSenderId: '17377405565',
    projectId: 'thexeason-cd2ab',
    storageBucket: 'thexeason-cd2ab.firebasestorage.app',
    iosBundleId: 'com.example.thexeasonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzQUeeExHC-wEGTD6jH6GbhM8Y1s_Dnyo',
    appId: '1:17377405565:ios:2395ccadefafecc9ad5f14',
    messagingSenderId: '17377405565',
    projectId: 'thexeason-cd2ab',
    storageBucket: 'thexeason-cd2ab.firebasestorage.app',
    iosBundleId: 'com.example.thexeasonapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCABkVDpSQJar5BjzijH2Re1d6sNuUY6pM',
    appId: '1:17377405565:web:9c226553ad8c6b70ad5f14',
    messagingSenderId: '17377405565',
    projectId: 'thexeason-cd2ab',
    authDomain: 'thexeason-cd2ab.firebaseapp.com',
    storageBucket: 'thexeason-cd2ab.firebasestorage.app',
    measurementId: 'G-DVCSSR2F26',
  );
}
